import os
import sys

def parse_layout(filepath):
    """解析版图文件，返回包含多边形坐标和层号的列表"""
    layout = []
    if not os.path.exists(filepath):
        print(f"Error: Layout file {filepath} not found.")
        sys.exit(1)
    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('%'):
                continue
            parts = line.split()
            if len(parts) >= 5:
                # format: x1, y1, x2, y2, layer_num
                layout.append({
                    'x1': float(parts[0]),
                    'y1': float(parts[1]),
                    'x2': float(parts[2]),
                    'y2': float(parts[3]),
                    'layer': int(parts[4])
                })
    return layout

def parse_rules(filepath):
    """解析层规则文件，检查数据一致性"""
    rules = {}
    if not os.path.exists(filepath):
        print(f"Error: Rule file {filepath} not found.")
        sys.exit(1)
    
    with open(filepath, 'r') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line or line.startswith('%') or line.startswith('['):
                continue
            parts = line.split()
            if len(parts) >= 8:
                try:
                    layer_num = int(parts[0])
                    enable = parts[2].lower() == 'true'
                    height = float(parts[3])
                    start_z = float(parts[4])
                    end_z = float(parts[5])
                    
                    if enable:
                        # 核心规则验证：end_z2 - start_z1 == height
                        if abs((end_z - start_z) - height) > 1e-5:
                            print(f"Error: Z-thickness mismatch in layer {layer_num} at line {line_num}.")
                            print(f"Details: end_z2 ({end_z}) - start_z1 ({start_z}) != height ({height}).")
                            print("Execution aborted.")
                            sys.exit(1)
                            
                    rules[layer_num] = {
                        'enable': enable,
                        'height': height,
                        'start_z': start_z,
                        'end_z': end_z
                    }
                except ValueError:
                    continue
    return rules

def parse_arch(filepath):
    """解析架构参数文件"""
    arch = {}
    if not os.path.exists(filepath):
        print(f"Error: Arch file {filepath} not found.")
        sys.exit(1)
    with open(filepath, 'r') as f:
        for line in f:
            line = line.split('%')[0].strip()
            if '=' in line:
                k, v = line.split('=')
                arch[k.strip()] = float(v.strip())
    return arch

class ObjBuilder:
    def __init__(self):
        self.lines = ["# CFET 3D Structural Mesh generated by gen_arch.py"]
        self.v_idx = 0

    def add_box(self, name, x1, x2, y1, y2, z1, z2):
        self.lines.append(f"\no {name}")
        vertices = [
            (x1, y1, z1), (x2, y1, z1), (x2, y2, z1), (x1, y2, z1),
            (x1, y1, z2), (x2, y1, z2), (x2, y2, z2), (x1, y2, z2)
        ]
        for v in vertices:
            self.lines.append(f"v {v[0]:.5f} {v[1]:.5f} {v[2]:.5f}")
        
        faces = [
            (1, 2, 3, 4), (5, 6, 7, 8),
            (1, 2, 6, 5), (2, 3, 7, 6),
            (3, 4, 8, 7), (4, 1, 5, 8)
        ]
        for f in faces:
            self.lines.append(f"f {f[0]+self.v_idx} {f[1]+self.v_idx} {f[2]+self.v_idx} {f[3]+self.v_idx}")
        self.v_idx += 8

    def add_wrap_around(self, name_prefix, x1, x2, ch_y1, ch_y2, ch_z1, ch_z2, thickness):
        """生成环绕沟道的4个子长方体 (Top, Bottom, Front, Back)，实现破开形貌"""
        # Top
        self.add_box(f"{name_prefix}_Top", x1, x2, ch_y1 - thickness, ch_y2 + thickness, ch_z2, ch_z2 + thickness)
        # Bottom
        self.add_box(f"{name_prefix}_Bot", x1, x2, ch_y1 - thickness, ch_y2 + thickness, ch_z1 - thickness, ch_z1)
        # Front (Y min side)
        self.add_box(f"{name_prefix}_Front", x1, x2, ch_y1 - thickness, ch_y1, ch_z1, ch_z2)
        # Back (Y max side)
        self.add_box(f"{name_prefix}_Back", x1, x2, ch_y2, ch_y2 + thickness, ch_z1, ch_z2)

    def write(self, filepath):
        with open(filepath, 'w') as f:
            f.write("\n".join(self.lines))


def main():
    # 用户可以在这里配置文件路径，或通过 sys.argv 传入
    layout_file = "./test1_gds.txt"
    rule_file = "./layer_rule_1.txt"
    arch_file = "./cfet_arch.txt"
    output_file = "./cfet_structure.obj"

    layout = parse_layout(layout_file)
    rules = parse_rules(rule_file)
    arch = parse_arch(arch_file)

    builder = ObjBuilder()

    # 1. 查找基础版图边界与栅极
    boundary_rect = next((item for item in layout if item['layer'] == 1), None)
    gate_rect = next((item for item in layout if item['layer'] == 7), None)

    if not boundary_rect or 1 not in rules:
        print("Error: Boundary (Layer 1) layout or rules missing.")
        sys.exit(1)

    # 2. 生成衬底 (Substrate)
    builder.add_box("Substrate", 
                    boundary_rect['x1'], boundary_rect['x2'], 
                    boundary_rect['y1'], boundary_rect['y2'], 
                    rules[1]['start_z'], rules[1]['end_z'])

    # 3. 参数回退逻辑 (Fallback for -1)
    num_channel_lower = int(arch.get('num_channel_lower', 2)) if arch.get('num_channel', 2) == -1 else int(arch.get('num_channel', 2))
    num_channel_upper = int(arch.get('num_channel_upeer', 2)) if arch.get('num_channel', 2) == -1 else int(arch.get('num_channel', 2))
    
    ch_length = arch.get('channel_lower_length', arch['channel_length']) if arch['channel_length'] == -1 else arch['channel_length']
    ch_width = arch.get('channel_lower_width', arch['channel_width']) if arch['channel_width'] == -1 else arch['channel_width']
    
    # 4. 计算沟道 (Channel) 坐标
    cx = arch['channel_center_x']
    cy = arch['channel_center_y']
    ch_x1, ch_x2 = cx - ch_length / 2, cx + ch_length / 2
    ch_y1, ch_y2 = cy - ch_width / 2, cy + ch_width / 2

    # 预计算所有沟道的 Z 轴高度区间
    channels_z = []
    current_z = 0.0
    # 下层 Channel Z 堆叠
    for _ in range(num_channel_lower):
        current_z += arch['channel_mdi_thickness']
        channels_z.append((current_z, current_z + arch['channel_thickness'], "Lower"))
        current_z += arch['channel_thickness']
    
    current_z += arch['mdi_thickness'] # 上下层分隔
    
    # 上层 Channel Z 堆叠
    for _ in range(num_channel_upper):
        current_z += arch['channel_mdi_thickness']
        channels_z.append((current_z, current_z + arch['channel_thickness'], "Upper"))
        current_z += arch['channel_thickness']

    # 5. 生成栅极 (Gate)
    gate_x1, gate_x2 = gate_rect['x1'], gate_rect['x2']
    if gate_rect and 7 in rules:
        builder.add_box("Gate_Common",
                        gate_x1, gate_x2,
                        gate_rect['y1'], gate_rect['y2'],
                        rules[7]['start_z'], rules[7]['end_z'])

    # 6. 生成 High-k 与 Inner Spacer
    hk_thickness = arch['high_k_thickness']
    is_thickness = arch['inner_spacer_thickness']

    for i, (z1, z2, layer_type) in enumerate(channels_z):
        # 沟道本体
        builder.add_box(f"Channel_{layer_type}_{i+1}", ch_x1, ch_x2, ch_y1, ch_y2, z1, z2)
        
        # High-K: 沿 x 轴分布于栅极覆盖区范围内，环绕沟道
        hk_x1, hk_x2 = gate_x1, gate_x2
        builder.add_wrap_around(f"HighK_{layer_type}_{i+1}", hk_x1, hk_x2, ch_y1, ch_y2, z1, z2, hk_thickness)
        
        # 内侧墙 (Inner Spacer): 位于 High-K 两侧 (X方向)，同样环绕并被沟道破开
        isp_left_x1, isp_left_x2 = hk_x1 - is_thickness, hk_x1
        isp_right_x1, isp_right_x2 = hk_x2, hk_x2 + is_thickness
        
        # 内侧墙的外壳范围与 High-K 保持一致
        builder.add_wrap_around(f"InnerSpacer_L_{layer_type}_{i+1}", isp_left_x1, isp_left_x2, ch_y1, ch_y2, z1, z2, hk_thickness)
        builder.add_wrap_around(f"InnerSpacer_R_{layer_type}_{i+1}", isp_right_x1, isp_right_x2, ch_y1, ch_y2, z1, z2, hk_thickness)

    # 7. 生成 源漏外延 (Source/Drain Epi)
    # 获取源漏在 Y 和 Z 方向的延伸增量
    sd_oy = arch.get('sd_lower_overgrowth_y', arch['sd_overgrowth_y']) if arch['sd_overgrowth_y'] == -1 else arch['sd_overgrowth_y']
    sd_z_up = arch.get('sd_lower_overgrowth_z_up', arch['sd_overgrowth_z_up']) if arch['sd_overgrowth_z_up'] == -1 else arch['sd_overgrowth_z_up']
    sd_z_down = arch.get('sd_lower_overgrowth_z_down', arch['sd_overgrowth_z_down']) if arch['sd_overgrowth_z_down'] == -1 else arch['sd_overgrowth_z_down']

    # 下层 S/D Z边界
    lower_zs = [z for z in channels_z if z[2] == "Lower"]
    sd_lower_z1 = lower_zs[0][0] - sd_z_down
    sd_lower_z2 = lower_zs[-1][1] + sd_z_up

    # 上层 S/D Z边界
    upper_zs = [z for z in channels_z if z[2] == "Upper"]
    sd_upper_z1 = upper_zs[0][0] - sd_z_down
    sd_upper_z2 = upper_zs[-1][1] + sd_z_up

    sd_y1, sd_y2 = ch_y1 - sd_oy, ch_y2 + sd_oy
    sd_left_x1, sd_left_x2 = boundary_rect['x1'], gate_x1 - is_thickness
    sd_right_x1, sd_right_x2 = gate_x2 + is_thickness, boundary_rect['x2']

    # 生成下层源漏
    builder.add_box("SD_Left_Lower", sd_left_x1, sd_left_x2, sd_y1, sd_y2, sd_lower_z1, sd_lower_z2)
    builder.add_box("SD_Right_Lower", sd_right_x1, sd_right_x2, sd_y1, sd_y2, sd_lower_z1, sd_lower_z2)

    # 生成上层源漏
    builder.add_box("SD_Left_Upper", sd_left_x1, sd_left_x2, sd_y1, sd_y2, sd_upper_z1, sd_upper_z2)
    builder.add_box("SD_Right_Upper", sd_right_x1, sd_right_x2, sd_y1, sd_y2, sd_upper_z1, sd_upper_z2)

    # 8. 输出文件
    builder.write(output_file)
    print(f"Structure successfully generated to {output_file}")

if __name__ == "__main__":
    main()