import os
import sys

def parse_layout(filepath):
    """解析版图文件，返回包含多边形坐标和层号的列表"""
    layout = []
    if not os.path.exists(filepath):
        print(f"Error: Layout file {filepath} not found.")
        sys.exit(1)
    with open(filepath, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('%'):
                continue
            parts = line.split()
            if len(parts) >= 5:
                layout.append({
                    'x1': float(parts[0]),
                    'y1': float(parts[1]),
                    'x2': float(parts[2]),
                    'y2': float(parts[3]),
                    'layer': int(parts[4])
                })
    return layout

def parse_rules(filepath):
    """解析层规则文件，检查数据一致性"""
    rules = {}
    if not os.path.exists(filepath):
        print(f"Error: Rule file {filepath} not found.")
        sys.exit(1)
    
    with open(filepath, 'r') as f:
        for line_num, line in enumerate(f, 1):
            line = line.strip()
            if not line or line.startswith('%') or line.startswith('['):
                continue
            parts = line.split()
            if len(parts) >= 8:
                try:
                    layer_num = int(parts[0])
                    enable = parts[2].lower() == 'true'
                    height = float(parts[3])
                    start_z = float(parts[4])
                    end_z = float(parts[5])
                    
                    if enable:
                        if abs((end_z - start_z) - height) > 1e-5:
                            print(f"Error: Z-thickness mismatch in layer {layer_num} at line {line_num}.")
                            sys.exit(1)
                            
                    rules[layer_num] = {
                        'enable': enable,
                        'height': height,
                        'start_z': start_z,
                        'end_z': end_z
                    }
                except ValueError:
                    continue
    return rules

def parse_arch(filepath):
    """解析架构参数文件"""
    arch = {}
    if not os.path.exists(filepath):
        print(f"Error: Arch file {filepath} not found.")
        sys.exit(1)
    with open(filepath, 'r') as f:
        for line in f:
            line = line.split('%')[0].strip()
            if '=' in line:
                k, v = line.split('=')
                arch[k.strip()] = float(v.strip())
    return arch

class ObjBuilder:
    def __init__(self, mtl_filename):
        mtl_basename = os.path.basename(mtl_filename)
        self.lines = [
            f"mtllib {mtl_basename}", 
            "# CFET 3D Structural Mesh generated by gen_arch.py"
        ]
        self.mtl_lines = ["# Material definitions for CFET Structure"]
        self.v_idx = 0

    def add_material(self, mat_name, r, g, b):
        self.mtl_lines.append(f"\nnewmtl {mat_name}")
        self.mtl_lines.append(f"Kd {r:.3f} {g:.3f} {b:.3f}")

    def add_box(self, name, x1, x2, y1, y2, z1, z2, mat_name=None):
        self.lines.append(f"\no {name}")
        if mat_name:
            self.lines.append(f"usemtl {mat_name}")
            
        vertices = [
            (x1, y1, z1), (x2, y1, z1), (x2, y2, z1), (x1, y2, z1),
            (x1, y1, z2), (x2, y1, z2), (x2, y2, z2), (x1, y2, z2)
        ]
        for v in vertices:
            self.lines.append(f"v {v[0]:.5f} {v[1]:.5f} {v[2]:.5f}")
        
        faces = [
            (1, 2, 3, 4), (5, 6, 7, 8),
            (1, 2, 6, 5), (2, 3, 7, 6),
            (3, 4, 8, 7), (4, 1, 5, 8)
        ]
        for f in faces:
            self.lines.append(f"f {f[0]+self.v_idx} {f[1]+self.v_idx} {f[2]+self.v_idx} {f[3]+self.v_idx}")
        self.v_idx += 8

    def add_wrap_around(self, name_prefix, x1, x2, ch_y1, ch_y2, ch_z1, ch_z2, thickness, mat_name=None):
        self.add_box(f"{name_prefix}_Top", x1, x2, ch_y1 - thickness, ch_y2 + thickness, ch_z2, ch_z2 + thickness, mat_name)
        self.add_box(f"{name_prefix}_Bot", x1, x2, ch_y1 - thickness, ch_y2 + thickness, ch_z1 - thickness, ch_z1, mat_name)
        self.add_box(f"{name_prefix}_Front", x1, x2, ch_y1 - thickness, ch_y1, ch_z1, ch_z2, mat_name)
        self.add_box(f"{name_prefix}_Back", x1, x2, ch_y2, ch_y2 + thickness, ch_z1, ch_z2, mat_name)

    def add_wall_with_holes(self, name_prefix, x1, x2, y1, y2, z1, z2, hole_y1, hole_y2, holes_z, mat_name=None):
        eps = 1e-6
        if hole_y1 - y1 > eps:
            self.add_box(f"{name_prefix}_YMin", x1, x2, y1, hole_y1, z1, z2, mat_name)
        if y2 - hole_y2 > eps:
            self.add_box(f"{name_prefix}_YMax", x1, x2, hole_y2, y2, z1, z2, mat_name)
        
        curr_z = z1
        for i, (hz1, hz2) in enumerate(holes_z):
            if hz1 - curr_z > eps:
                self.add_box(f"{name_prefix}_ZMid_{i}", x1, x2, hole_y1, hole_y2, curr_z, hz1, mat_name)
            curr_z = hz2
            
        if z2 - curr_z > eps:
            self.add_box(f"{name_prefix}_ZMid_Top", x1, x2, hole_y1, hole_y2, curr_z, z2, mat_name)

    def write(self, obj_filepath, mtl_filepath):
        os.makedirs(os.path.dirname(obj_filepath), exist_ok=True)
        with open(obj_filepath, 'w') as f:
            f.write("\n".join(self.lines))
        with open(mtl_filepath, 'w') as f:
            f.write("\n".join(self.mtl_lines))

def main():
    layout_file = "./gds/test1_gds.txt"
    rule_file = "./rules/layer_rule_1.txt"
    arch_file = "./rules/cfet_arch.txt"
    output_obj = "./output/cfet_structure.obj"
    output_mtl = "./output/cfet_materials.mtl"

    layout = parse_layout(layout_file)
    rules = parse_rules(rule_file)
    arch = parse_arch(arch_file)

    builder = ObjBuilder(output_mtl)

    mat_sub = "Mat_Substrate"
    mat_gate = "Mat_Gate"
    mat_ch = "Mat_Channel"
    mat_hk = "Mat_HighK"
    mat_isp = "Mat_InnerSpacer"
    mat_sd = "Mat_SDEpi"

    builder.add_material(mat_sub, 0.7, 0.7, 0.7)  
    builder.add_material(mat_gate, 0.8, 0.2, 0.2) 
    builder.add_material(mat_ch, 0.2, 0.6, 1.0)   
    builder.add_material(mat_hk, 0.9, 0.8, 0.2)   
    builder.add_material(mat_isp, 0.2, 0.8, 0.4)  
    builder.add_material(mat_sd, 0.9, 0.5, 0.1)   

    boundary_rect = next((item for item in layout if item['layer'] == 1), None)
    gate_rect = next((item for item in layout if item['layer'] == 7), None)

    if not boundary_rect or 1 not in rules:
        print("Error: Boundary (Layer 1) layout or rules missing.")
        sys.exit(1)

    builder.add_box("Substrate", 
                    boundary_rect['x1'], boundary_rect['x2'], 
                    boundary_rect['y1'], boundary_rect['y2'], 
                    rules[1]['start_z'], rules[1]['end_z'], mat_sub)

    num_channel_lower = int(arch.get('num_channel_lower', 2)) if arch.get('num_channel', 2) == -1 else int(arch.get('num_channel', 2))
    num_channel_upper = int(arch.get('num_channel_upeer', 2)) if arch.get('num_channel', 2) == -1 else int(arch.get('num_channel', 2))
    ch_length = arch.get('channel_lower_length', arch['channel_length']) if arch['channel_length'] == -1 else arch['channel_length']
    ch_width = arch.get('channel_lower_width', arch['channel_width']) if arch['channel_width'] == -1 else arch['channel_width']
    
    cx = arch['channel_center_x']
    cy = arch['channel_center_y']
    ch_x1, ch_x2 = cx - ch_length / 2, cx + ch_length / 2
    ch_y1, ch_y2 = cy - ch_width / 2, cy + ch_width / 2

    channels_z = []
    current_z = 0.0
    for _ in range(num_channel_lower):
        current_z += arch['channel_mdi_thickness']
        channels_z.append((current_z, current_z + arch['channel_thickness'], "Lower"))
        current_z += arch['channel_thickness']
    
    current_z += arch['mdi_thickness'] 
    
    for _ in range(num_channel_upper):
        current_z += arch['channel_mdi_thickness']
        channels_z.append((current_z, current_z + arch['channel_thickness'], "Upper"))
        current_z += arch['channel_thickness']

    # 提取栅极真实的物理边界
    gate_x1, gate_x2 = gate_rect['x1'], gate_rect['x2']
    gate_y1, gate_y2 = gate_rect['y1'], gate_rect['y2']
    gate_z1, gate_z2 = rules[7]['start_z'], rules[7]['end_z']

    if gate_rect and 7 in rules:
        builder.add_box("Gate_Common",
                        gate_x1, gate_x2,
                        gate_y1, gate_y2,
                        gate_z1, gate_z2, mat_gate)

    hk_thickness = arch['high_k_thickness']
    is_thickness = arch['inner_spacer_thickness']

    for i, (z1, z2, layer_type) in enumerate(channels_z):
        # 生成沟道与独立环绕沟道的 High-k 外壳
        builder.add_box(f"Channel_{layer_type}_{i+1}", ch_x1, ch_x2, ch_y1, ch_y2, z1, z2, mat_ch)
        builder.add_wrap_around(f"HighK_{layer_type}_{i+1}", gate_x1, gate_x2, ch_y1, ch_y2, z1, z2, hk_thickness, mat_hk)

    sd_oy = arch.get('sd_lower_overgrowth_y', arch['sd_overgrowth_y']) if arch['sd_overgrowth_y'] == -1 else arch['sd_overgrowth_y']
    sd_z_up = arch.get('sd_lower_overgrowth_z_up', arch['sd_overgrowth_z_up']) if arch['sd_overgrowth_z_up'] == -1 else arch['sd_overgrowth_z_up']
    sd_z_down = arch.get('sd_lower_overgrowth_z_down', arch['sd_overgrowth_z_down']) if arch['sd_overgrowth_z_down'] == -1 else arch['sd_overgrowth_z_down']

    lower_zs = [z for z in channels_z if z[2] == "Lower"]
    upper_zs = [z for z in channels_z if z[2] == "Upper"]
    
    sd_lower_z1, sd_lower_z2 = lower_zs[0][0] - sd_z_down, lower_zs[-1][1] + sd_z_up
    sd_upper_z1, sd_upper_z2 = upper_zs[0][0] - sd_z_down, upper_zs[-1][1] + sd_z_up
    sd_y1, sd_y2 = ch_y1 - sd_oy, ch_y2 + sd_oy

    all_holes = [(z[0], z[1]) for z in channels_z]
    
    isp_left_x1, isp_left_x2 = gate_x1 - is_thickness, gate_x1
    isp_right_x1, isp_right_x2 = gate_x2, gate_x2 + is_thickness
    
    # 1. 贯穿整体高度的连续内侧墙，严格对齐Gate的Y和Z边界
    builder.add_wall_with_holes("InnerSpacer_L", isp_left_x1, isp_left_x2, gate_y1, gate_y2, gate_z1, gate_z2, ch_y1, ch_y2, all_holes, mat_isp)
    builder.add_wall_with_holes("InnerSpacer_R", isp_right_x1, isp_right_x2, gate_y1, gate_y2, gate_z1, gate_z2, ch_y1, ch_y2, all_holes, mat_isp)

    # 2. 贯穿整体高度的连续 High-k 侧壁衬垫，严格对齐Gate的Y和Z边界
    hk_left_x1, hk_left_x2 = gate_x1, gate_x1 + hk_thickness
    hk_right_x1, hk_right_x2 = gate_x2 - hk_thickness, gate_x2

    builder.add_wall_with_holes("HighK_Liner_L", hk_left_x1, hk_left_x2, gate_y1, gate_y2, gate_z1, gate_z2, ch_y1, ch_y2, all_holes, mat_hk)
    builder.add_wall_with_holes("HighK_Liner_R", hk_right_x1, hk_right_x2, gate_y1, gate_y2, gate_z1, gate_z2, ch_y1, ch_y2, all_holes, mat_hk)

    # 3. 独立分离的源漏外延层
    sd_left_x1, sd_left_x2 = boundary_rect['x1'], isp_left_x1
    sd_right_x1, sd_right_x2 = isp_right_x2, boundary_rect['x2']

    builder.add_box("SD_Left_Lower", sd_left_x1, sd_left_x2, sd_y1, sd_y2, sd_lower_z1, sd_lower_z2, mat_sd)
    builder.add_box("SD_Right_Lower", sd_right_x1, sd_right_x2, sd_y1, sd_y2, sd_lower_z1, sd_lower_z2, mat_sd)
    builder.add_box("SD_Left_Upper", sd_left_x1, sd_left_x2, sd_y1, sd_y2, sd_upper_z1, sd_upper_z2, mat_sd)
    builder.add_box("SD_Right_Upper", sd_right_x1, sd_right_x2, sd_y1, sd_y2, sd_upper_z1, sd_upper_z2, mat_sd)

    builder.write(output_obj, output_mtl)
    print(f"Structure obj and mtl generated to {os.path.dirname(output_obj)}")

if __name__ == "__main__":
    main()