from __future__ import annotations
import json, math, re
from pathlib import Path

root=Path(__file__).resolve().parents[1]; va=root/'Hspice/va'; source=(va/'parameter_network1.html').read_text(encoding='utf-8')
a=source.index('const DATA=')+len('const DATA='); b=source.index(';const canvas',a); data=json.loads(source[a:b])
params={p['name']:p for p in data['params']}; formulas=data['formulas']
nodes=[]; edges=[]
for i,p in enumerate(data['params']):
    # Two outer rings make NN and physical declarations visually distinct.
    ring=520 if p['nn'] else 390; ang=i*(math.pi*(3-math.sqrt(5)))
    nodes.append({'id':'p:'+p['name'],'label':p['name'],'kind':'nn' if p['nn'] else 'physical','x':math.cos(ang)*ring,'y':math.sin(ang)*ring,'meta':p})
for i,f in enumerate(formulas):
    ang=i*(math.pi*(3-math.sqrt(5))); r=70+250*math.sqrt((i+.5)/max(1,len(formulas)))
    fid='f:'+str(f['line'])+':'+str(i); nodes.append({'id':fid,'label':'L'+str(f['line']),'kind':'formula','x':math.cos(ang)*r,'y':math.sin(ang)*r,'meta':f})
    for dep in f['deps']:
        if dep in params: edges.append(['p:'+dep,fid])
    if f['target'] in params: edges.append([fid,'p:'+f['target']])
payload={'nodes':nodes,'edges':edges,'stats':{'params':len(params),'formulas':len(formulas),'edges':len(edges)}}
html=r'''<!doctype html><meta charset="utf-8"><title>NMOS 全量公式连接图</title><style>*{box-sizing:border-box}body{margin:0;background:#06111d;color:#dbe8f5;font:14px "Microsoft YaHei",Arial;overflow:hidden}#net{display:block;width:100vw;height:100vh}#bar{position:fixed;top:16px;left:16px;width:330px;background:#0b1d30ed;border:1px solid #31536f;border-radius:10px;padding:13px;z-index:2}h1{font-size:17px;margin:0 0 5px}p{margin:5px 0;color:#9bb6ce;line-height:1.45}input{width:100%;background:#10283e;border:1px solid #3c6180;border-radius:7px;padding:8px;color:#fff;margin:8px 0}button{padding:7px 9px;background:#133552;border:1px solid #426889;color:#e7f2fc;border-radius:6px;cursor:pointer}.tag{display:inline-block;margin:5px 8px 0 0;font-size:12px}.dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:4px}.tip{position:fixed;right:16px;bottom:16px;background:#0b1d30ed;border:1px solid #31536f;border-radius:9px;padding:10px;max-width:420px;color:#b9d0e3}.selected{color:#ffd36b}</style><canvas id="net"></canvas><div id="bar"><h1>NMOS 全量参数—公式连接图</h1><p id="stats"></p><input id="q" list="names" placeholder="搜索任意参数或公式行号"><datalist id="names"></datalist><button id="find">定位并高亮</button> <button id="home">重置视图</button><p><span class="tag"><i class="dot" style="background:#4eb6df"></i>非 NN 参数</span><span class="tag"><i class="dot" style="background:#bd81f0"></i>NN 参数</span><span class="tag"><i class="dot" style="background:#e6a94e"></i>公式</span></p><p>滚轮缩放；拖动平移；单击任意点查看该节点的直接依赖。全量图刻意保留密度，局部追踪用于阅读公式。</p></div><div class="tip" id="tip">未选择节点。</div><script>const D=__DATA__;const c=document.querySelector('#net'),x=c.getContext('2d'),q=document.querySelector('#q'),tip=document.querySelector('#tip');let w,h,scale=.72,ox=0,oy=0,drag=null,sel=null;const map=new Map(D.nodes.map(n=>[n.id,n]));D.nodes.forEach(n=>document.querySelector('#names').insertAdjacentHTML('beforeend',`<option value="${n.label}">`));document.querySelector('#stats').textContent=`${D.stats.params} 参数 · ${D.stats.formulas} 公式节点 · ${D.stats.edges} 连接边`;
function resize(){w=c.width=innerWidth*devicePixelRatio;h=c.height=innerHeight*devicePixelRatio;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);if(!ox){ox=innerWidth/2;oy=innerHeight/2}draw()}addEventListener('resize',resize);function S(n){return{x:n.x*scale+ox,y:n.y*scale+oy}}function draw(){x.clearRect(0,0,innerWidth,innerHeight);x.fillStyle='#06111d';x.fillRect(0,0,innerWidth,innerHeight);let related=sel?new Set(D.edges.filter(e=>e[0]===sel||e[1]===sel).flat()):null;D.edges.forEach(e=>{let a=map.get(e[0]),b=map.get(e[1]);if(!a||!b)return;let A=S(a),B=S(b),hit=sel&&(e[0]===sel||e[1]===sel);x.beginPath();x.moveTo(A.x,A.y);x.lineTo(B.x,B.y);x.globalAlpha=sel?(hit?1:.045):.17;x.strokeStyle=hit?(e[0]===sel?'#6fe7b0':'#ffd36b'):'#5d84a2';x.lineWidth=hit?3:1;x.stroke()});x.globalAlpha=1;D.nodes.forEach(n=>{let p=S(n),hit=related&&related.has(n.id);x.beginPath();x.arc(p.x,p.y,hit?4.6:2.2,0,Math.PI*2);x.fillStyle=n.kind==='nn'?'#bd81f0':n.kind==='formula'?'#e6a94e':'#4eb6df';x.globalAlpha=sel&&!hit?.10:1;x.fill();if(hit||scale>1.4){x.fillStyle='#eaf4ff';x.font='11px sans-serif';x.fillText(n.label,p.x+6,p.y-4)}});x.globalAlpha=1}function pick(px,py){let best=null,d=15;D.nodes.forEach(n=>{let p=S(n),z=Math.hypot(p.x-px,p.y-py);if(z<d){d=z;best=n}});return best}function choose(n){sel=n.id;let m=n.meta,inc=D.edges.filter(e=>e[0]===n.id).length,out=D.edges.filter(e=>e[1]===n.id).length;tip.innerHTML=`<b class="selected">${n.label}</b><br>${n.kind==='formula'?(m.expr||'公式节点'):`${n.kind==='nn'?'NN 参数':'非 NN 参数'} · 默认值：${m.value||'—'} · 源行：${m.line||'—'}`}<br>直接入边：${out} · 直接出边：${inc}`;draw()}c.addEventListener('wheel',e=>{e.preventDefault();let k=e.deltaY<0?1.14:.88;scale=Math.max(.15,Math.min(6,scale*k));draw()},{passive:false});c.addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,ox,oy};c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(!drag)return;ox=drag.ox+e.clientX-drag.x;oy=drag.oy+e.clientY-drag.y;draw()});c.addEventListener('pointerup',e=>{let moved=drag&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>4;drag=null;if(!moved){let n=pick(e.clientX,e.clientY);if(n)choose(n)}});document.querySelector('#find').onclick=()=>{let s=q.value.trim(),n=D.nodes.find(x=>x.label===s)||D.nodes.find(x=>x.label.toLowerCase().includes(s.toLowerCase()));if(n){ox=innerWidth/2-n.x*scale;oy=innerHeight/2-n.y*scale;choose(n)}};document.querySelector('#home').onclick=()=>{scale=.72;ox=innerWidth/2;oy=innerHeight/2;sel=null;tip.textContent='未选择节点。';draw()};resize();</script>'''
(va/'parameter_network_full.html').write_text(html.replace('__DATA__',json.dumps(payload,ensure_ascii=False)),encoding='utf-8')
print(f"Wrote full graph: {len(nodes)} nodes, {len(edges)} edges")
