from __future__ import annotations
import json, re
from pathlib import Path

root=Path(__file__).resolve().parents[1]; src=root/'Hspice/va/fusion_ic_nmos_lvt.va'; out=root/'Hspice/va/parameter_network1.html'
decl={}; formulas=[]
dr=re.compile(r'^\s*(parameter\s+)?real\s+(.+?);')
ar=re.compile(r'^\s*([A-Za-z_]\w*)\s*=\s*(.+?);')
words=re.compile(r'\b[A-Za-z_]\w*\b'); skip={'real','parameter','if','else','begin','end','pow','sqrt','exp','log','abs','max','min'}
for line,raw in enumerate(src.read_text(encoding='utf-8',errors='replace').splitlines(),1):
    code=raw.split('//',1)[0].strip(); m=dr.match(raw)
    if m:
        for item in m.group(2).split(','):
            x=re.match(r'\s*([A-Za-z_]\w*)\s*(?:=\s*(.*))?',item)
            if x: decl[x.group(1)]={'name':x.group(1),'value':(x.group(2)or'—').strip(),'line':line,'nn':x.group(1).startswith('nn') or x.group(1).startswith('neuron') or x.group(1).endswith('_nor') or bool(re.match(r'(?:sce|clm|qua|mob|cv|gidl)_output\d+',x.group(1)))}
    m=ar.match(code)
    if m:
        deps=sorted({w for w in words.findall(m.group(2)) if w in decl and w not in skip and w!=m.group(1)})
        if deps: formulas.append({'target':m.group(1),'deps':deps,'expr':code,'line':line})
params=list(decl.values()); nn=[p for p in params if p['nn']]; physical=[p for p in params if not p['nn']]
def nn_stats(prefix):
    p=[x['name'] for x in nn if x['name'].startswith(prefix)]
    w=[x for x in p if x.startswith(prefix+'w')]; b=[x for x in p if x.startswith(prefix+'b')]
    return {'weights':len(w),'biases':len(b),'total':len(p)}
stats={k:nn_stats(k) for k in ['nnsce','nnclm','nnqua','nnmob','nncv']}
data={'params':params,'formulas':formulas,'stats':{'all':len(params),'physical':len(physical),'nn':len(nn),'formulas':len(formulas),'models':stats}}

page=r'''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NMOS 公式依赖网络</title><style>
*{box-sizing:border-box}body{margin:0;background:#07121f;color:#e4edf7;font:14px/1.45 "Microsoft YaHei",Arial}.app{height:100vh;display:grid;grid-template:62px 1fr/285px 1fr 330px}.top{grid-column:1/4;display:flex;align-items:center;gap:16px;padding:0 22px;background:#0b1b2d;border-bottom:1px solid #26435d}.top h1{font-size:18px;margin:0}.top span{color:#9bb4cc}.pill{margin-left:auto;background:#153c37;color:#a7f5ce;border-radius:16px;padding:5px 11px}.side{padding:16px;background:#091827;border-right:1px solid #26435d;overflow:auto}.right{border-right:0;border-left:1px solid #26435d}.side h3{font-size:12px;text-transform:uppercase;letter-spacing:.1em;color:#89a8c5;margin:16px 0 7px}.side h3:first-child{margin-top:0}input,select{width:100%;background:#10263a;color:#e4edf7;border:1px solid #345775;border-radius:8px;padding:9px}button{width:100%;margin:5px 0;padding:9px;border-radius:8px;border:1px solid #345775;background:#102a42;color:#e4edf7;text-align:left;cursor:pointer}button:hover{background:#1a4160}.legend{margin:8px 0;color:#a9c0d6}.sw{display:inline-block;width:11px;height:11px;border-radius:3px;margin-right:7px}.canvas{position:relative;overflow:hidden;background:radial-gradient(circle at 45% 40%,#142d48,#07121f 66%)}svg{position:absolute;inset:0;width:100%;height:100%}.node{position:absolute;transform:translate(-50%,-50%);width:138px;min-height:48px;padding:7px 9px;border:1px solid #4c799b;border-radius:9px;background:#123451;text-align:center;font-weight:600;cursor:pointer;box-shadow:0 5px 18px #0005}.node small{display:block;font-size:10px;font-weight:400;color:#b0c9dc}.formula{border-color:#d99a42;background:#493117}.nn{border-color:#a26ada;background:#2c1e48}.output{border-color:#45ba85;background:#133d35}.edge{stroke:#5d88a8;stroke-width:2;marker-end:url(#arrow)}.edge.nn{stroke:#af76e7;stroke-dasharray:6 5;marker-end:url(#arrowNN)}.edge.formula{stroke:#d6a151;marker-end:url(#arrowF)}.hint{position:absolute;bottom:15px;left:15px;background:#0c1b2ce8;border:1px solid #31506c;border-radius:8px;padding:7px 10px;color:#9fb9d1;font-size:12px}.title{font-size:19px;margin:0 0 4px}.muted{color:#9bb3ca}.mono{background:#07111e;padding:10px;border-radius:8px;white-space:pre-wrap;overflow:auto;color:#b9d3e8;font:12px/1.5 ui-monospace,Consolas}.chip{display:inline-block;border:1px solid #3e6583;border-radius:12px;padding:3px 7px;margin:3px;font:11px ui-monospace;color:#bfe4f5;cursor:pointer}.empty{color:#91abc3;padding-top:70px;text-align:center}.matrix{border:1px solid #a26ada;background:#201831;border-radius:8px;padding:8px;margin:8px 0;color:#d8c4ef}.matrix b{color:#fff}@media(max-width:950px){.app{grid-template:62px 1fr/230px 1fr}.right{display:none}.top{grid-column:1/3}}
</style><body><main class="app"><header class="top"><h1>NMOS 参数—公式依赖网络</h1><span>蓝：物理参数　橙：公式　紫：神经网络矩阵/层　绿：终端量</span><b class="pill" id="count"></b></header><aside class="side"><h3>定位全量参数</h3><input id="search" list="params" placeholder="输入 L、EOT_0、nnmobw1_1_1 …"><datalist id="params"></datalist><button id="focus">查看该参数的公式网络</button><button id="overview">返回全局语义网络</button><h3>NN 矩阵模型</h3><div id="matrices"></div><h3>阅读方式</h3><p class="muted">箭头始终穿过橙色公式节点。点击任何节点后，右侧显示原始 Verilog-A 表达式、行号、输入和输出。</p><div class="legend"><i class="sw" style="background:#123451"></i>非 NN 参数</div><div class="legend"><i class="sw" style="background:#2c1e48"></i>NN 层 / 权重矩阵</div><div class="legend"><i class="sw" style="background:#493117"></i>公式</div></aside><section class="canvas" id="canvas"><svg><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0 0L0 6L7 3z" fill="#5d88a8"/></marker><marker id="arrowNN" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0 0L0 6L7 3z" fill="#af76e7"/></marker><marker id="arrowF" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0 0L0 6L7 3z" fill="#d6a151"/></marker><g id="edges"></g></svg><div class="hint">总览：物理主链与 NN 矩阵支路。搜索参数：切换为该参数的局部公式超图。</div></section><aside class="side right" id="detail"><div class="empty">选择参数、公式或矩阵节点查看详情。</div></aside></main><script>const DATA=__DATA__;const canvas=document.querySelector('#canvas'),edgeLayer=document.querySelector('#edges'),detail=document.querySelector('#detail'),search=document.querySelector('#search');const pos=new Map();document.querySelector('#count').textContent=`${DATA.stats.all} total declarations · ${DATA.stats.formulas} formulas`;DATA.params.forEach(p=>document.querySelector('#params').insertAdjacentHTML('beforeend',`<option value="${p.name}">`));const modelNames={nnsce:'SCE',nnclm:'CLM / VSAT',nnqua:'Quantum / GIDL',nnmob:'Mobility',nncv:'C-V'};Object.entries(DATA.stats.models).forEach(([k,v])=>document.querySelector('#matrices').insertAdjacentHTML('beforeend',`<div class="matrix"><b>${modelNames[k]}</b><br>权重矩阵 ${v.weights} · 偏置 ${v.biases}<br><span class="muted">折叠显示 ${v.total} 个 NN 参数</span></div>`));
function clear(){canvas.querySelectorAll('.node').forEach(x=>x.remove());edgeLayer.innerHTML='';pos.clear()}function add(n){let d=document.createElement('div');d.className='node '+n.type;d.style.left=n.x+'%';d.style.top=n.y+'%';d.innerHTML=n.label+(n.sub?`<small>${n.sub}</small>`:'');d.onclick=()=>show(n);canvas.append(d);pos.set(n.id,n);return n}function line(a,b,kind=''){let A=pos.get(a),B=pos.get(b);if(!A||!B)return;let l=document.createElementNS('http://www.w3.org/2000/svg','line');l.setAttribute('x1',A.x+'%');l.setAttribute('y1',A.y+'%');l.setAttribute('x2',B.x+'%');l.setAttribute('y2',B.y+'%');l.setAttribute('class','edge '+kind);edgeLayer.append(l)}function show(n){if(n.formula){detail.innerHTML=`<h2 class="title">公式节点</h2><p class="muted">fusion_ic_nmos_lvt.va · 第 ${n.formula.line} 行</p><div class="mono">${n.formula.expr}</div><h3>输入</h3>${n.formula.deps.map(x=>`<span class="chip" onclick="focusName('${x}')">${x}</span>`).join('')}<h3>输出</h3><span class="chip" onclick="focusName('${n.formula.target}')">${n.formula.target}</span>`;return}if(n.matrix){detail.innerHTML=`<h2 class="title">${n.label}</h2><p class="muted">规则神经网络矩阵块</p><div class="mono">${n.matrix.weights} 个权重\n${n.matrix.biases} 个偏置\n${n.matrix.total} 个折叠 NN 参数</div><p>点击搜索框中任一 nn 权重或神经元，可追踪其实际公式关系。</p>`;return}let p=DATA.params.find(x=>x.name===n.id);if(!p){detail.innerHTML=`<h2 class="title">${n.label}</h2><p>${n.sub||''}</p>`;return}let F=DATA.formulas.filter(f=>f.target===p.name||f.deps.includes(p.name));detail.innerHTML=`<h2 class="title">${p.name}</h2><p class="muted">${p.nn?'NN 参数':'非 NN 参数'} · 第 ${p.line} 行</p><div class="mono">默认值：${p.value}</div><h3>参与公式 (${F.length})</h3>${F.length?F.map(f=>`<div class="mono" style="margin:7px 0">L${f.line}: ${f.expr}</div>`).join(''):'未在已解析的单行赋值式中出现'}`}
function overview(){clear();let N=[['geo','几何 / 工艺','L · W · TGAA · WGAA',10,38,'physical'],['fg','几何有效量公式','Weff / Ach / Lg',28,38,'formula'],['elec','电静力 / SCE','EOT · Vth · DVT',47,23,'physical'],['mob','迁移率','U0 · UA · EU',47,54,'physical'],['fnn','NN 输入归一化','L / W / TGAA',26,75,'nn'],['nsce','NN SCE 矩阵','W / B → SCE outputs',47,72,'nn'],['nmm','NN Mobility 矩阵','W / B → mob outputs',65,72,'nn'],['ncv','NN C-V 矩阵','W / B → cv outputs',82,72,'nn'],['fiv','I-V 公式','Dvsat / IDS',68,38,'formula'],['fcv','C-V 公式','QG / QD / QS',82,46,'formula'],['out','终端量','IDS · QG · QD · QS',93,40,'output']];N.forEach(x=>add({id:x[0],label:x[1],sub:x[2],x:x[3],y:x[4],type:x[5]}));[['geo','fg'],['fg','elec','formula'],['fg','mob','formula'],['elec','fiv','formula'],['mob','fiv','formula'],['fiv','out','formula'],['fcv','out','formula'],['geo','fnn','nn'],['fnn','nsce','nn'],['fnn','nmm','nn'],['fnn','ncv','nn'],['nsce','elec','nn'],['nmm','mob','nn'],['ncv','fcv','nn']].forEach(e=>line(...e))}function local(name){let p=DATA.params.find(x=>x.name===name);if(!p){return}clear();let F=DATA.formulas.filter(f=>f.target===name||f.deps.includes(name)).slice(0,12);add({id:name,label:name,sub:p.nn?'NN parameter':'physical parameter',x:50,y:50,type:p.nn?'nn':'physical'});let rel=[];F.forEach(f=>{let id='f'+f.line;add({id,label:`公式 L${f.line}`,sub:f.expr.length>42?f.expr.slice(0,42)+'…':f.expr,x:f.target===name?70:30,y:15+rel.length*12,type:'formula',formula:f});line(f.target===name?id:name,f.target===name?name:id,'formula');f.deps.forEach(dep=>{if(dep===name)return;let pid='p'+dep;if(!pos.has(pid)){add({id:pid,label:dep,sub:'formula input',x:f.target===name?25:75,y:15+rel.length*12,type:DATA.params.find(x=>x.name===dep)?.nn?'nn':'physical'});rel.push(dep)}line(pid,id)});});show({id:name})}window.focusName=local;document.querySelector('#focus').onclick=()=>local(search.value.trim());search.addEventListener('change',()=>local(search.value.trim()));document.querySelector('#overview').onclick=overview;overview();</script></body></html>'''
out.write_text(page.replace('__DATA__',json.dumps(data,ensure_ascii=False)),encoding='utf-8')
print(f'Wrote {out}: {len(params)} declarations, {len(formulas)} formula nodes')
