import os
import sys

from gen_sram_sde import EPS, SDEWriter, fmt, parse_arch, parse_layer_rules, parse_layout


DEVICE_MAP = (
    ("PG1", "nmos", "upper", "GATE_PG1", "SDN_PG1_OUTER", "SDN_PG1_PD1_SHARED"),
    ("PD1", "nmos", "upper", "GATE_PD1_PU1", "SDN_PG1_PD1_SHARED", "SDN_PD1_OUTER"),
    ("PU1", "pmos", "lower", "GATE_PD1_PU1", "SDP_PU1_NODE", "SDP_PU1_POWER"),
    ("PD2", "nmos", "upper", "GATE_PD2_PU2", "SDN_PD2_OUTER", "SDN_PD2_PG2_SHARED"),
    ("PU2", "pmos", "lower", "GATE_PD2_PU2", "SDP_PU2_POWER", "SDP_PU2_NODE"),
    ("PG2", "nmos", "upper", "GATE_PG2", "SDN_PD2_PG2_SHARED", "SDN_PG2_OUTER"),
)

ROUTING_LAYERS = (16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 51, 52, 53)


def safe(text):
    return "".join(ch if ch.isalnum() or ch == "_" else "_" for ch in str(text))


class StandardBuilder:
    def __init__(self, layout, rules, arch):
        self.layout = layout
        self.rules = rules
        self.arch = arch
        self.sde = SDEWriter()
        self.boundary = self.get_boundary()
        self.gates = {rect["label"]: rect for rect in layout.get(111, [])}
        self.sd_n = {rect["label"]: rect for rect in layout.get(121, [])}
        self.sd_p = {rect["label"]: rect for rect in layout.get(122, [])}
        self.sheet_z = self.compute_sheet_z()
        self.built_gates = set()
        self.built_sd = set()
        self.sd_regions = []
        self.channel_regions = []
        self.routing_regions = {}

    def a(self, key, default=None):
        if key in self.arch:
            return self.arch[key]
        if default is not None:
            return default
        raise KeyError(f"Missing required arch parameter: {key}")

    def rule(self, layer):
        value = self.rules.get(layer)
        if not value or not value["enable"]:
            raise ValueError(f"Layer {layer} is missing or disabled.")
        return value

    def get_boundary(self):
        rects = self.layout.get(1, [])
        if len(rects) != 1:
            raise ValueError("sram_standard requires exactly one layer-1 boundary.")
        return rects[0]

    def compute_sheet_z(self):
        thickness = float(self.a("channel_thickness"))
        gap = float(self.a("channel_vertical_gap"))
        lower = []
        z = 0.0
        for _ in range(int(float(self.a("num_channel_lower")))):
            z += gap
            lower.append((z, z + thickness))
            z += thickness
        z += gap + float(self.a("mdi_thickness"))
        upper = []
        for _ in range(int(float(self.a("num_channel_upper")))):
            z += gap
            upper.append((z, z + thickness))
            z += thickness
        return {"lower": lower, "upper": upper}

    def build(self):
        self.sde.comment("Generated by AutoLDM/LD/gen_sram_standard_sde.py")
        self.sde.comment("Source of all x/y geometry: gds/sram_standard_6t_gds.txt")
        self.sde.comment("x: CPP direction, y: Cell Height direction, z: CFET stack.")
        self.sde.comment("DTCO-oriented abstract structure; not a foundry-qualified model.")
        self.sde.add("(sde:clear)")
        self.sde.add('(sdegeo:set-default-boolean "ABA")')
        self.build_dielectrics()
        self.build_devices()
        self.build_routing()
        self.add_pin_contacts()
        self.add_doping()
        self.add_meshing()
        return self.sde

    def build_dielectrics(self):
        self.sde.section("Dielectric envelope")
        b = self.boundary
        spans = (
            ("ILD_Backside", -0.064, 0.000),
            ("ILD_FEOL_Lower", 0.000, 0.070),
            ("ILD_MDI", 0.070, 0.094),
            ("ILD_FEOL_Upper", 0.094, 0.140),
            ("ILD_MOL", 0.140, 0.200),
            ("ILD_BEOL", 0.200, 0.380),
        )
        for name, z1, z2 in spans:
            self.sde.cuboid(name, b["x1"], b["y1"], z1, b["x2"], b["y2"], z2, "SiO2", False)

    def build_devices(self):
        self.sde.section("Six-transistor common-gate CFET geometry")
        for device_name, device_type, tier, gate_label, left_label, right_label in DEVICE_MAP:
            gate = self.gates.get(gate_label)
            sd_map = self.sd_p if device_type == "pmos" else self.sd_n
            left_sd = sd_map.get(left_label)
            right_sd = sd_map.get(right_label)
            if not gate or not left_sd or not right_sd:
                raise ValueError(
                    f"{device_name} mapping is incomplete: "
                    f"gate={gate_label}, left={left_label}, right={right_label}."
                )
            self.build_gate(gate)
            self.build_sd(left_sd, device_type, tier)
            self.build_sd(right_sd, device_type, tier)
            self.build_channel_and_spacer(device_name, gate, left_sd, right_sd, tier)

    def build_gate(self, gate):
        key = (
            gate["x1"], gate["y1"], gate["x2"], gate["y2"], gate["net"]
        )
        if key in self.built_gates:
            return
        gate_rule = self.rule(7)
        name = f"Gate_{safe(gate['label'])}_{safe(gate['net'])}"
        self.sde.cuboid(
            name,
            gate["x1"], gate["y1"], gate_rule["start_z"],
            gate["x2"], gate["y2"], gate_rule["end_z"],
            str(self.a("gate_material")),
        )
        hk = float(self.a("high_k_thickness"))
        z1, z2 = gate_rule["start_z"], gate_rule["end_z"]
        self.sde.cuboid(f"HighK_{safe(gate['label'])}_XMin", gate["x1"] - hk, gate["y1"], z1, gate["x1"], gate["y2"], z2, "HfO2", False)
        self.sde.cuboid(f"HighK_{safe(gate['label'])}_XMax", gate["x2"], gate["y1"], z1, gate["x2"] + hk, gate["y2"], z2, "HfO2", False)
        self.sde.cuboid(f"HighK_{safe(gate['label'])}_YMin", gate["x1"], gate["y1"] - hk, z1, gate["x2"], gate["y1"], z2, "HfO2", False)
        self.sde.cuboid(f"HighK_{safe(gate['label'])}_YMax", gate["x1"], gate["y2"], z1, gate["x2"], gate["y2"] + hk, z2, "HfO2", False)
        self.built_gates.add(key)

    def build_sd(self, rect, device_type, tier):
        key = (
            device_type, tier, rect["net"],
            rect["x1"], rect["y1"], rect["x2"], rect["y2"],
        )
        if key in self.built_sd:
            return
        if tier == "upper":
            z1 = float(self.a("upper_sd_z1"))
            z2 = float(self.a("upper_sd_z2"))
            material = str(self.a("upper_sd_material"))
        else:
            z1 = float(self.a("lower_sd_z1"))
            z2 = float(self.a("lower_sd_z2"))
            material = str(self.a("lower_sd_material"))
        name = f"SD_{safe(rect['label'])}_{safe(rect['net'])}_{tier}"
        self.sde.cuboid(
            name, rect["x1"], rect["y1"], z1,
            rect["x2"], rect["y2"], z2, material, False,
        )
        self.sd_regions.append((name, device_type))
        self.built_sd.add(key)

    def build_channel_and_spacer(self, device_name, gate, left_sd, right_sd, tier):
        hk = float(self.a("high_k_thickness"))
        x_segments = (
            ("Left", left_sd["x2"], gate["x1"] - hk),
            ("Right", gate["x2"] + hk, right_sd["x1"]),
        )
        y1 = max(left_sd["y1"], right_sd["y1"])
        y2 = min(left_sd["y2"], right_sd["y2"])
        if y2 <= y1:
            raise ValueError(f"{device_name} left/right S/D do not share a channel y interval.")
        material = str(self.a("upper_channel_material" if tier == "upper" else "lower_channel_material"))
        gate_rule = self.rule(7)
        for side, x1, x2 in x_segments:
            if x2 <= x1:
                raise ValueError(f"{device_name} {side} channel length is not positive.")
            sheets = self.sheet_z[tier]
            for index, (z1, z2) in enumerate(sheets):
                name = f"CH_{device_name}_{side}_{index}"
                self.sde.cuboid(name, x1, y1, z1, x2, y2, z2, material, False)
                self.channel_regions.append(name)
            self.build_inner_spacer(device_name, side, x1, x2, y1, y2, gate, sheets, gate_rule)

    def build_inner_spacer(self, device_name, side, x1, x2, y1, y2, gate, sheets, gate_rule):
        material = str(self.a("inner_spacer_material"))
        prefix = f"InnerSpacer_{device_name}_{side}"
        self.sde.cuboid(prefix + "_YMin", x1, gate["y1"], gate_rule["start_z"], x2, y1, gate_rule["end_z"], material, False)
        self.sde.cuboid(prefix + "_YMax", x1, y2, gate_rule["start_z"], x2, gate["y2"], gate_rule["end_z"], material, False)
        current = gate_rule["start_z"]
        for index, (sheet_z1, sheet_z2) in enumerate(sheets):
            self.sde.cuboid(prefix + f"_ZGap_{index}", x1, y1, current, x2, y2, sheet_z1, material, False)
            current = max(current, sheet_z2)
        self.sde.cuboid(prefix + f"_ZGap_{len(sheets)}", x1, y1, current, x2, y2, gate_rule["end_z"], material, False)

    def build_routing(self):
        self.sde.section("Layout-driven MD/BMD/MRW and interconnect")
        for layer in ROUTING_LAYERS:
            rule = self.rule(layer)
            for index, rect in enumerate(self.layout.get(layer, [])):
                name = f"{safe(rule['layer_name'])}_{safe(rect['label'])}_{safe(rect['net'])}_{index}"
                created = self.sde.cuboid(
                    name,
                    rect["x1"], rect["y1"], rule["start_z"],
                    rect["x2"], rect["y2"], rule["end_z"],
                    rule["material"],
                )
                if created:
                    self.routing_regions[rect["label"]] = {
                        "name": name,
                        "rect": rect,
                        "rule": rule,
                    }

    def add_pin_contacts(self):
        self.sde.section("External electrical contacts")
        pins = (
            ("BL", "M0_BL", "top"),
            ("BLB", "M0_BLB", "top"),
            ("Q", "M2_Q", "top"),
            ("QB", "M2_QB", "top"),
            ("WL", "M2_WL", "top"),
            ("VDD", "BM0_VDD", "bottom"),
            ("VSS", "M0_VSS_BOTTOM", "top"),
            ("VSS", "M0_VSS_TOP", "top"),
        )
        defined = set()
        for contact_name, label, face in pins:
            region = self.routing_regions.get(label)
            if not region:
                raise ValueError(f"Contact target {label} was not generated.")
            if contact_name not in defined:
                self.sde.add(f'(sdegeo:define-contact-set "{contact_name}" 4 (color:rgb 1 0 0) "##")')
                defined.add(contact_name)
            rect = region["rect"]
            rule = region["rule"]
            x = (rect["x1"] + rect["x2"]) / 2.0
            y = (rect["y1"] + rect["y2"]) / 2.0
            z = rule["z2"] if "z2" in rule else rule["end_z"]
            if face == "bottom":
                z = rule["start_z"]
            self.sde.add(
                f'(sdegeo:set-contact (find-face-id (position {fmt(x)} {fmt(y)} {fmt(z)})) "{contact_name}")'
            )

    def add_doping(self):
        if not bool(self.a("doping_enable", True)):
            return
        self.sde.section("Source/drain doping")
        groups = {
            "nmos": (
                "NMOS_SD_Doping",
                str(self.a("nmos_doping_species")),
                float(self.a("nmos_doping_concentration")),
            ),
            "pmos": (
                "PMOS_SD_Doping",
                str(self.a("pmos_doping_species")),
                float(self.a("pmos_doping_concentration")),
            ),
        }
        for device_type, (profile, species, concentration) in groups.items():
            regions = [name for name, kind in self.sd_regions if kind == device_type]
            self.sde.add(f'(sdedr:define-constant-profile "{profile}" "{species}" {concentration:.6g})')
            for index, region in enumerate(regions):
                self.sde.add(
                    f'(sdedr:define-constant-profile-region "Place_{profile}_{index}" '
                    f'"{profile}" "{region}")'
                )

    def add_meshing(self):
        if not bool(self.a("meshing_enable", True)):
            return
        self.sde.section("Meshing")
        b = self.boundary
        z_min = min(region["z1"] for region in self.sde.regions)
        z_max = max(region["z2"] for region in self.sde.regions)
        self.sde.add(
            f'(sdedr:define-refeval-window "Global_Win" "Cuboid" '
            f'(position {fmt(b["x1"] - 0.02)} {fmt(b["y1"] - 0.02)} {fmt(z_min - 0.02)}) '
            f'(position {fmt(b["x2"] + 0.02)} {fmt(b["y2"] + 0.02)} {fmt(z_max + 0.02)}))'
        )
        self.sde.add(
            f'(sdedr:define-refinement-size "Global_Mesh_Size" '
            f'{float(self.a("global_mesh_max_x")):.6g} {float(self.a("global_mesh_max_y")):.6g} {float(self.a("global_mesh_max_z")):.6g} '
            f'{float(self.a("global_mesh_min_x")):.6g} {float(self.a("global_mesh_min_y")):.6g} {float(self.a("global_mesh_min_z")):.6g})'
        )
        self.sde.add('(sdedr:define-refinement-placement "Global_Mesh_Place" "Global_Mesh_Size" "Global_Win")')
        self.sde.add(
            f'(sdedr:define-refeval-window "Core_Win" "Cuboid" '
            f'(position {fmt(b["x1"])} {fmt(b["y1"])} {fmt(float(self.a("lower_sd_z1")))}) '
            f'(position {fmt(b["x2"])} {fmt(b["y2"])} {fmt(float(self.a("upper_sd_z2")))}) )'
        )
        self.sde.add(
            f'(sdedr:define-refinement-size "Core_Mesh_Size" '
            f'{float(self.a("core_mesh_max_x")):.6g} {float(self.a("core_mesh_max_y")):.6g} {float(self.a("core_mesh_max_z")):.6g} '
            f'{float(self.a("core_mesh_min_x")):.6g} {float(self.a("core_mesh_min_y")):.6g} {float(self.a("core_mesh_min_z")):.6g})'
        )
        self.sde.add('(sdedr:define-refinement-placement "Core_Mesh_Place" "Core_Mesh_Size" "Core_Win")')
        model_name = str(self.a("mesh_output_name"))
        self.sde.add(f'(sde:save-model "{model_name}")')
        self.sde.add(
            f'(sde:build-mesh "{self.a("mesh_engine")}" "{self.a("mesh_options")}" '
            f'"{model_name}")'
        )


def check_layer_z_continuity(rules):
    chains = ((18, 19, 20, 21, 22, 23, 24, 25), (53, 52, 51))
    for chain in chains:
        ordered = [rules[layer] for layer in chain]
        for lower, upper in zip(ordered, ordered[1:]):
            if abs(lower["end_z"] - upper["start_z"]) > 1e-9:
                raise ValueError(
                    f"Layer z gap/overlap: {lower['layer_name']} ends at {lower['end_z']}, "
                    f"{upper['layer_name']} starts at {upper['start_z']}."
                )


def default_paths(base):
    return {
        "layout": os.path.join(base, "gds", "sram_standard_6t_gds.txt"),
        "arch": os.path.join(base, "rules", "sram_standard_arch.txt"),
        "rules": os.path.join(base, "rules", "sram_standard_layer_rule.txt"),
        "output": os.path.join(base, "SDE", "sram_standard_6t_sde.cmd"),
    }


def main(argv):
    base = os.path.dirname(os.path.abspath(__file__))
    paths = default_paths(base)
    for index, key in enumerate(("layout", "arch", "rules", "output"), 1):
        if len(argv) > index:
            paths[key] = argv[index]
    for key in ("layout", "arch", "rules"):
        if not os.path.exists(paths[key]):
            raise FileNotFoundError(f"Missing {key}: {paths[key]}")
    layout = parse_layout(paths["layout"])
    arch = parse_arch(paths["arch"])
    rules = parse_layer_rules(paths["rules"])
    check_layer_z_continuity(rules)
    writer = StandardBuilder(layout, rules, arch).build()
    writer.write(paths["output"])
    print(f"Generated standard SRAM SDE command: {paths['output']}")


if __name__ == "__main__":
    try:
        main(sys.argv)
    except Exception as exc:
        print(f"Error: {exc}", file=sys.stderr)
        raise SystemExit(1)
