; Generated by AutoLDM/LD/gen_sde.py from guide1/guide2 and rules.
; x: Source-Gate-Drain, y: gate width/channel width, z: vertical stacking.
(sde:clear)

; ----------------------------------------------------------------------
; Geometry
; ----------------------------------------------------------------------
(sdegeo:create-cuboid (position 0.00000 0.00000 -0.10000) (position 0.04200 0.06200 0.00000) "Silicon" "Substrate_1")
(sdegeo:create-cuboid (position 0.01400 0.01200 0.00000) (position 0.02800 0.05100 0.16000) "Tungsten" "Gate_Common")
(sdegeo:create-cuboid (position 0.00800 0.02100 0.01200) (position 0.01200 0.04200 0.01800) "Silicon" "ChannelLower_0_L")
(sdegeo:create-cuboid (position 0.03000 0.02100 0.01200) (position 0.03400 0.04200 0.01800) "Silicon" "ChannelLower_0_R")
(sdegeo:create-cuboid (position 0.00800 0.02100 0.03000) (position 0.01200 0.04200 0.03600) "Silicon" "ChannelLower_1_L")
(sdegeo:create-cuboid (position 0.03000 0.02100 0.03000) (position 0.03400 0.04200 0.03600) "Silicon" "ChannelLower_1_R")
(sdegeo:create-cuboid (position 0.00800 0.02100 0.10000) (position 0.01200 0.04200 0.10600) "Silicon" "ChannelUpper_0_L")
(sdegeo:create-cuboid (position 0.03000 0.02100 0.10000) (position 0.03400 0.04200 0.10600) "Silicon" "ChannelUpper_0_R")
(sdegeo:create-cuboid (position 0.00800 0.02100 0.11800) (position 0.01200 0.04200 0.12400) "Silicon" "ChannelUpper_1_L")
(sdegeo:create-cuboid (position 0.03000 0.02100 0.11800) (position 0.03400 0.04200 0.12400) "Silicon" "ChannelUpper_1_R")
(sdegeo:create-cuboid (position 0.01200 0.01200 0.00000) (position 0.01400 0.05100 0.16000) "HfO2" "HighK_Gate_Left")
(sdegeo:create-cuboid (position 0.02800 0.01200 0.00000) (position 0.03000 0.05100 0.16000) "HfO2" "HighK_Gate_Right")
(sdegeo:create-cuboid (position 0.01400 0.01000 0.00000) (position 0.02800 0.01200 0.16000) "HfO2" "HighK_Gate_Front")
(sdegeo:create-cuboid (position 0.01400 0.05100 0.00000) (position 0.02800 0.05300 0.16000) "HfO2" "HighK_Gate_Back")
(sdegeo:create-cuboid (position 0.00800 0.01200 0.00000) (position 0.01200 0.02100 0.16000) "Si3N4" "InnerSpacer_L_YMin")
(sdegeo:create-cuboid (position 0.00800 0.04200 0.00000) (position 0.01200 0.05100 0.16000) "Si3N4" "InnerSpacer_L_YMax")
(sdegeo:create-cuboid (position 0.00800 0.02100 0.00000) (position 0.01200 0.04200 0.01200) "Si3N4" "InnerSpacer_L_ZGap_0")
(sdegeo:create-cuboid (position 0.00800 0.02100 0.01800) (position 0.01200 0.04200 0.03000) "Si3N4" "InnerSpacer_L_ZGap_1")
(sdegeo:create-cuboid (position 0.00800 0.02100 0.03600) (position 0.01200 0.04200 0.10000) "Si3N4" "InnerSpacer_L_ZGap_2")
(sdegeo:create-cuboid (position 0.00800 0.02100 0.10600) (position 0.01200 0.04200 0.11800) "Si3N4" "InnerSpacer_L_ZGap_3")
(sdegeo:create-cuboid (position 0.00800 0.02100 0.12400) (position 0.01200 0.04200 0.16000) "Si3N4" "InnerSpacer_L_ZGap_4")
(sdegeo:create-cuboid (position 0.03000 0.01200 0.00000) (position 0.03400 0.02100 0.16000) "Si3N4" "InnerSpacer_R_YMin")
(sdegeo:create-cuboid (position 0.03000 0.04200 0.00000) (position 0.03400 0.05100 0.16000) "Si3N4" "InnerSpacer_R_YMax")
(sdegeo:create-cuboid (position 0.03000 0.02100 0.00000) (position 0.03400 0.04200 0.01200) "Si3N4" "InnerSpacer_R_ZGap_0")
(sdegeo:create-cuboid (position 0.03000 0.02100 0.01800) (position 0.03400 0.04200 0.03000) "Si3N4" "InnerSpacer_R_ZGap_1")
(sdegeo:create-cuboid (position 0.03000 0.02100 0.03600) (position 0.03400 0.04200 0.10000) "Si3N4" "InnerSpacer_R_ZGap_2")
(sdegeo:create-cuboid (position 0.03000 0.02100 0.10600) (position 0.03400 0.04200 0.11800) "Si3N4" "InnerSpacer_R_ZGap_3")
(sdegeo:create-cuboid (position 0.03000 0.02100 0.12400) (position 0.03400 0.04200 0.16000) "Si3N4" "InnerSpacer_R_ZGap_4")
(sdegeo:create-cuboid (position 0.00000 0.01600 0.00600) (position 0.00800 0.04700 0.04200) "SiGe" "SD_Lower_Left")
(sdegeo:create-cuboid (position 0.03400 0.01600 0.00600) (position 0.04200 0.04700 0.04200) "SiGe" "SD_Lower_Right")
(sdegeo:create-cuboid (position 0.00000 0.01600 0.09400) (position 0.00800 0.04700 0.13000) "Silicon" "SD_Upper_Left")
(sdegeo:create-cuboid (position 0.03400 0.01600 0.09400) (position 0.04200 0.04700 0.13000) "Silicon" "SD_Upper_Right")

; ----------------------------------------------------------------------
; Contacts
; ----------------------------------------------------------------------
(sdegeo:define-contact-set "Contact_Gate_Common_Top_0" 4 (color:rgb 1 0 0) "##")
(sdegeo:define-contact-set "Contact_Gate_Common_Bot_0" 4 (color:rgb 1 0 0) "##")
(sdegeo:set-contact (find-face-id (position 0.02100 0.03150 0.16000)) "Contact_Gate_Common_Top_0")
(sdegeo:set-contact (find-face-id (position 0.02100 0.03150 0.00000)) "Contact_Gate_Common_Bot_0")

; ----------------------------------------------------------------------
; Doping
; ----------------------------------------------------------------------
(sdedr:define-constant-profile "SD_Upper_Doping" "ArsenicActiveConcentration" 8e+19)
(sdedr:define-constant-profile-region "Place_SD_U_L" "SD_Upper_Doping" "SD_Upper_Left")
(sdedr:define-constant-profile-region "Place_SD_U_R" "SD_Upper_Doping" "SD_Upper_Right")
(sdedr:define-constant-profile "SD_Lower_Doping" "BoronActiveConcentration" 8e+19)
(sdedr:define-constant-profile-region "Place_SD_L_L" "SD_Lower_Doping" "SD_Lower_Left")
(sdedr:define-constant-profile-region "Place_SD_L_R" "SD_Lower_Doping" "SD_Lower_Right")

; ----------------------------------------------------------------------
; Meshing
; ----------------------------------------------------------------------
(sdedr:define-refeval-window "Global_Win" "Cuboid" (position -0.02000 -0.02000 -0.12000) (position 0.06200 0.08200 0.18000))
(sdedr:define-refinement-size "Global_Mesh_Size" 0.02 0.02 0.02 0.01 0.01 0.01)
(sdedr:define-refinement-placement "Global_Mesh_Place" "Global_Mesh_Size" "Global_Win")
(sdedr:define-refeval-window "Core_Win" "Cuboid" (position 0.00000 0.00000 0.00000) (position 0.04200 0.06200 0.20000))
(sdedr:define-refinement-size "Core_Mesh_Size" 0.002 0.002 0.002 0.001 0.001 0.001)
(sdedr:define-refinement-placement "Core_Mesh_Place" "Core_Mesh_Size" "Core_Win")
(sde:build-mesh "snmesh" "-a -c boxmethod" "n@node@_cfet_structure")
